# Idexing

In [1]:
import numpy as np
a1 = np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [2]:
a2 = np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [4]:
a1[2]

2

In [5]:
a2[1]

array([5, 6, 7, 8, 9])

In [6]:
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

# Slicing

In [7]:
a1[1:3]

array([1, 2])

In [8]:
a1[1::2] # starts from index 1 and goes to the end with a jump of 2

array([1, 3])

### 2D numpy array

In [9]:
a2[:,1] # column 1 only

array([1, 6])

In [10]:
a2[:,0::4] # 1st and last column

array([[0, 4],
       [5, 9]])

In [11]:
a2[1,3:5] # only 8 and 9 

array([8, 9])

### 3D numpy array

In [12]:
a3[1,0,:]

array([ 9, 10, 11])

In [13]:
a3[2,0::2,:]

array([[18, 19, 20],
       [24, 25, 26]])

In [14]:
a3[0::2,0,:]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [15]:
a3[-1,:,-1] # [index of matrices: rows of those matrices: columns of those matrices]

array([20, 23, 26])

In [16]:
a3[1,:,0:2]

array([[ 9, 10],
       [12, 13],
       [15, 16]])

In [17]:
a3[0::2,:,0:2]

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[18, 19],
        [21, 22],
        [24, 25]]])

# Iteration

In [18]:
for i in a2:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]


In [19]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [20]:
for i in np.nditer(a3): # its prints all the elements of ndarray
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### ravel, transpose function

In [21]:
np.ravel(a3) # convert ndarray to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [22]:
a2.transpose()
a2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Stacking 
- hstack
- vstack
- dstack for depth(3D)

In [23]:
a4 = np.arange(10).reshape(2,5)
a5 = np.arange(10,20).reshape(2,5)
a4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
a5

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [26]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
np.hsplit(a4,5)

[array([[0],
        [5]]),
 array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]])]

In [28]:
np.vsplit(a5,2)

[array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]