# What is NumPy?
- NumPy (Numerical Python) is a Python library used for working with arrays.
# Why Use NumPy if we already have lists in python?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
# Why is NumPy Faster Than Lists?
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# NumPy Creating Arrays
There are some functions through which you can create a ndarray like.
- array()
- arange()
- ones()
- zeros()
- random()
- linspace()
- identity()

- 0-D arrays or scalar e.g 42
- 1-D arrays [1, 2, 3, 4, 5]
- 2-D arrays [[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]]
- 3-D arrays [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [13]:
import numpy as np
# a = np.array((1,2,3,4))
a = np.array([1,2,3,4]) # 1d
b = np.array([1,2,3,4], dtype='float')
c = np.array([[1,2,3,4],[5,6,7,8]]) # 2d
print(a)
print(b)
print(c)

[1 2 3 4]
[1. 2. 3. 4.]
[[1 2 3 4]
 [5 6 7 8]]


In [15]:
import numpy as np
a = np.arange(5,15) # (start,end-1)
b =  np.arange(5,15,2) # (start,end-1,step-size)
print(a)
print(b)

[ 5  6  7  8  9 10 11 12 13 14]
[ 5  7  9 11 13]
