# Numpy array attrributes
- ndim
- shape
- size
- itemsize
- dtype

In [1]:
import numpy as np
x = np.array([2,34,5,9])
y = np.array([[[2,34,5],[4,6,7]],[[2,34,5],[4,6,7]]])
print(x.ndim) # ndim means no of dimensions
print(y.ndim)

1
3


In [2]:
print(x.shape) # no of items in each dimensions
print(y.shape) # (2,2,3) --> 2 sets of 2x3 matrices

(4,)
(2, 2, 3)


In [3]:
print(x.size) # total no of elements in ndarray
print(y.size)

4
12


In [4]:
print(x.itemsize) # size of item in bytes (bydefault it's int32 = 4bytes)
w = np.arange(1,5,dtype = np.float64)
print(w, w.itemsize)

4
[1. 2. 3. 4.] 8


In [5]:
print(x.dtype)
print(w.dtype)

int32
float64


# Changing datatypes
- you can use astype function

In [6]:
print(w.dtype)
w = w.astype(np.int32)
print(w.dtype)

float64
int32


# Array operations
- scalar operations (one operand is array and other is a scalar/number)
- vector opeartions (both the operand will be the numpy arrays)

In [7]:
# scalar operations (arithmetic and relational operations)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(5,9).reshape(2,2)
print(a1)
print(a1*5)
print(a1>3)

[[1 2]
 [3 4]]
[[ 5 10]
 [15 20]]
[[False False]
 [False  True]]


In [8]:
# vector operations
print(a1+a2) # arithmetic 
print(a1==a2) # relational
print(a1<=a2)

[[ 6  8]
 [10 12]]
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


# Array functions
- min, max, sum, prod (can be applied on entire array or row/column wise)
- mean, median, std, var
- log, exp
- sin/cos/tan
- dot (for dot product)
- round, floor, ceil

In [17]:
v = np.random.random((2,3))
print(v)
v = np.round(v*10)
print(v)

[[0.88212689 0.13457101 0.53384349]
 [0.11101174 0.29328801 0.03704078]]
[[9. 1. 5.]
 [1. 3. 0.]]


In [10]:
print(np.max(v))
print(np.prod(v))

8.0
0.0


In [11]:
# to find sum/max/min/prod either column or row wise
# axis = 0 for col, axis = 1 for row
print(np.max(v,axis=1))
print(np.prod(v,axis=0))
print(np.sum(v,axis=1))

[8. 8.]
[ 0. 64. 15.]
[13. 16.]


In [12]:
a = np.array([1,2,3,6,1])
print(np.mean(a))
print(np.std(a))
print(np.median(a))

2.6
1.854723699099141
2.0


In [13]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ,  0.96017029,  0.54030231])

In [14]:
m1 = np.arange(1,11).reshape(2,5)
m2 = np.arange(11,21).reshape(5,2)

print(np.dot(m1,m2)) # it is necessary that the columns in first matrix must be same as the rows in second one for a dot product

[[245 260]
 [620 660]]


In [22]:
print(v)
print(np.round(v*100))

[[9. 1. 5.]
 [1. 3. 0.]]
[[900. 100. 500.]
 [100. 300.   0.]]


In [37]:
print(np.floor(v))

[[9. 1. 5.]
 [1. 3. 0.]]


In [36]:
print(np.ceil(v))

[[9. 1. 5.]
 [1. 3. 0.]]
